# Generated by Django 5.2 on 2025-04-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(related_name='players', to='league.league'),
        ),
    ]
