# Generated by Django 5.2 on 2025-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='players', to='league.league'),
        ),
    ]
